# Dropout

In [1]:
import torch


class MLP(torch.nn.Module):
    def __init__(self, num_features, num_classes):
        super().__init__()

        self.all_layers = torch.nn.Sequential(
            torch.nn.Linear(num_features, 10),
            torch.nn.ReLU(),
            torch.nn.Dropout(0.5),
            
            # output layer
            torch.nn.Linear(10, num_classes),
        )

    def forward(self, x):
        logits = self.all_layers(x)
        return logits

In [2]:
torch.manual_seed(123)

model = MLP(num_features=5, num_classes=2)

## Dropout during training

In [3]:
x = torch.tensor([1., 0.3, 2.4, -1.1, -0.8])

In [4]:
model(x)

tensor([-0.1564, -0.2977], grad_fn=<AddBackward0>)

In [5]:
model(x)

tensor([0.1359, 0.0523], grad_fn=<AddBackward0>)

## Disable dropout during inference

In [6]:
model.eval();

In [7]:
model(x)

tensor([-0.0458, -0.1777], grad_fn=<AddBackward0>)

In [8]:
model(x)

tensor([-0.0458, -0.1777], grad_fn=<AddBackward0>)

Note: during inference, it's also recommended to use either `torch.no_grad()` or `torch.inference_mode()` context so that gradient tracking is disabled. (Not used above to demonstrate that `.eval()` disables dropout during inference.

In [9]:
with torch.inference_mode():
    print(model(x))

tensor([-0.0458, -0.1777])
