# Random Weight Initialization

### Without Random Seed

In [1]:
import torch 


layer = torch.nn.Linear(2, 3)
print(layer.weight)

Parameter containing:
tensor([[ 0.1458, -0.5813],
        [-0.3033,  0.0979],
        [-0.0911, -0.2116]], requires_grad=True)


In [2]:
layer = torch.nn.Linear(2, 3)
print(layer.weight)

Parameter containing:
tensor([[ 0.1760, -0.6285],
        [-0.1398, -0.0959],
        [ 0.3127,  0.4303]], requires_grad=True)


### With Random Seed

In [3]:
torch.manual_seed(123)

layer = torch.nn.Linear(2, 3)
print(layer.weight)

Parameter containing:
tensor([[-0.2883,  0.0234],
        [-0.3512,  0.2667],
        [-0.6025,  0.5183]], requires_grad=True)


In [4]:
torch.manual_seed(123)

layer = torch.nn.Linear(2, 3)
print(layer.weight)

Parameter containing:
tensor([[-0.2883,  0.0234],
        [-0.3512,  0.2667],
        [-0.6025,  0.5183]], requires_grad=True)
